
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

cr3_arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6
        
    constraints:
        goal_time: 0.6
        # vel_tolerance is 0 for due to the movegroup/follow_joint_trajectory/goal tolerance is empty
        stopped_velocity_tolerance: 0
        joint1: {trajectory: 0.1, goal: 0.1}
        joint2: {trajectory: 0.1, goal: 0.1}
        joint3: {trajectory: 0.1, goal: 0.1}
        joint4: {trajectory: 0.1, goal: 0.1}
        joint5: {trajectory: 0.1, goal: 0.1}
        joint6: {trajectory: 0.1, goal: 0.1}

    gains:
        joint1: { p: 12000, d: 50, i: 0.0, i_clamp: 10000 }
        joint2: { p: 30000, d: 100, i: 0.02, i_clamp: 10000 }
        joint3: { p: 18000, d: 50, i: 0.01, i_clamp: 1 }
        joint4: { p: 18000, d: 70, i: 0.01, i_clamp: 10000 }
        joint5: { p: 12000, d: 70, i: 0.01, i_clamp: 1 }
        joint6: { p: 7000, d: 50, i: 0.01, i_clamp: 1 }


cr3_hand_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
        - joint8
        - joint9
    gains:
        panda_finger_joint1: { p: 5, d: 3.0, i: 0, i_clamp: 1 }
        panda_finger_joint2: { p: 5, d: 1.0, i: 0, i_clamp: 1 }

joint_group_position_controller:
    type: position_controllers/JointGroupPositionController
    joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6

