controller_list:
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - joint8
      - joint9
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
initial:  # Define initial robot poses.
#  - group: hand
#    pose: home

  []