- desc: 'He is a man. His apparent age is 30 years old. He is wearing glasses. He
    is wearing glasses. He is wearing a red and white shirt. '
  location:
    orientation: {w: 0.482696883723855, x: 0.0, y: 0.0, z: 0.8757874847491707}
    position: {x: 2.3363442548079467, y: 1.1881521227950074, z: 0}
  name: Sam
  role: guest_1
