// Generated by gencpp from file tesr_ros_cr3_pkg/VisualServoResponse.msg
// DO NOT EDIT!


#ifndef TESR_ROS_CR3_PKG_MESSAGE_VISUALSERVORESPONSE_H
#define TESR_ROS_CR3_PKG_MESSAGE_VISUALSERVORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tesr_ros_cr3_pkg
{
template <class ContainerAllocator>
struct VisualServoResponse_
{
  typedef VisualServoResponse_<ContainerAllocator> Type;

  VisualServoResponse_()
    : success(false)  {
    }
  VisualServoResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::tesr_ros_cr3_pkg::VisualServoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tesr_ros_cr3_pkg::VisualServoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct VisualServoResponse_

typedef ::tesr_ros_cr3_pkg::VisualServoResponse_<std::allocator<void> > VisualServoResponse;

typedef boost::shared_ptr< ::tesr_ros_cr3_pkg::VisualServoResponse > VisualServoResponsePtr;
typedef boost::shared_ptr< ::tesr_ros_cr3_pkg::VisualServoResponse const> VisualServoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tesr_ros_cr3_pkg::VisualServoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tesr_ros_cr3_pkg::VisualServoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tesr_ros_cr3_pkg::VisualServoResponse_<ContainerAllocator1> & lhs, const ::tesr_ros_cr3_pkg::VisualServoResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tesr_ros_cr3_pkg::VisualServoResponse_<ContainerAllocator1> & lhs, const ::tesr_ros_cr3_pkg::VisualServoResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tesr_ros_cr3_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tesr_ros_cr3_pkg::VisualServoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tesr_ros_cr3_pkg::VisualServoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tesr_ros_cr3_pkg::VisualServoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tesr_ros_cr3_pkg::VisualServoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tesr_ros_cr3_pkg::VisualServoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tesr_ros_cr3_pkg::VisualServoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tesr_ros_cr3_pkg::VisualServoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::tesr_ros_cr3_pkg::VisualServoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::tesr_ros_cr3_pkg::VisualServoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tesr_ros_cr3_pkg/VisualServoResponse";
  }

  static const char* value(const ::tesr_ros_cr3_pkg::VisualServoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tesr_ros_cr3_pkg::VisualServoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::tesr_ros_cr3_pkg::VisualServoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tesr_ros_cr3_pkg::VisualServoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VisualServoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tesr_ros_cr3_pkg::VisualServoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tesr_ros_cr3_pkg::VisualServoResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TESR_ROS_CR3_PKG_MESSAGE_VISUALSERVORESPONSE_H
