// Generated by gencpp from file tesr_ros_cr3_pkg/VisualServo.msg
// DO NOT EDIT!


#ifndef TESR_ROS_CR3_PKG_MESSAGE_VISUALSERVO_H
#define TESR_ROS_CR3_PKG_MESSAGE_VISUALSERVO_H

#include <ros/service_traits.h>


#include <tesr_ros_cr3_pkg/VisualServoRequest.h>
#include <tesr_ros_cr3_pkg/VisualServoResponse.h>


namespace tesr_ros_cr3_pkg
{

struct VisualServo
{

typedef VisualServoRequest Request;
typedef VisualServoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VisualServo
} // namespace tesr_ros_cr3_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tesr_ros_cr3_pkg::VisualServo > {
  static const char* value()
  {
    return "ac73de7c264c9f54be33ec7cca98a512";
  }

  static const char* value(const ::tesr_ros_cr3_pkg::VisualServo&) { return value(); }
};

template<>
struct DataType< ::tesr_ros_cr3_pkg::VisualServo > {
  static const char* value()
  {
    return "tesr_ros_cr3_pkg/VisualServo";
  }

  static const char* value(const ::tesr_ros_cr3_pkg::VisualServo&) { return value(); }
};


// service_traits::MD5Sum< ::tesr_ros_cr3_pkg::VisualServoRequest> should match
// service_traits::MD5Sum< ::tesr_ros_cr3_pkg::VisualServo >
template<>
struct MD5Sum< ::tesr_ros_cr3_pkg::VisualServoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tesr_ros_cr3_pkg::VisualServo >::value();
  }
  static const char* value(const ::tesr_ros_cr3_pkg::VisualServoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tesr_ros_cr3_pkg::VisualServoRequest> should match
// service_traits::DataType< ::tesr_ros_cr3_pkg::VisualServo >
template<>
struct DataType< ::tesr_ros_cr3_pkg::VisualServoRequest>
{
  static const char* value()
  {
    return DataType< ::tesr_ros_cr3_pkg::VisualServo >::value();
  }
  static const char* value(const ::tesr_ros_cr3_pkg::VisualServoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tesr_ros_cr3_pkg::VisualServoResponse> should match
// service_traits::MD5Sum< ::tesr_ros_cr3_pkg::VisualServo >
template<>
struct MD5Sum< ::tesr_ros_cr3_pkg::VisualServoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tesr_ros_cr3_pkg::VisualServo >::value();
  }
  static const char* value(const ::tesr_ros_cr3_pkg::VisualServoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tesr_ros_cr3_pkg::VisualServoResponse> should match
// service_traits::DataType< ::tesr_ros_cr3_pkg::VisualServo >
template<>
struct DataType< ::tesr_ros_cr3_pkg::VisualServoResponse>
{
  static const char* value()
  {
    return DataType< ::tesr_ros_cr3_pkg::VisualServo >::value();
  }
  static const char* value(const ::tesr_ros_cr3_pkg::VisualServoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TESR_ROS_CR3_PKG_MESSAGE_VISUALSERVO_H
