// Generated by gencpp from file cr3_moveit_control/cr3_place.msg
// DO NOT EDIT!


#ifndef CR3_MOVEIT_CONTROL_MESSAGE_CR3_PLACE_H
#define CR3_MOVEIT_CONTROL_MESSAGE_CR3_PLACE_H

#include <ros/service_traits.h>


#include <cr3_moveit_control/cr3_placeRequest.h>
#include <cr3_moveit_control/cr3_placeResponse.h>


namespace cr3_moveit_control
{

struct cr3_place
{

typedef cr3_placeRequest Request;
typedef cr3_placeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cr3_place
} // namespace cr3_moveit_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cr3_moveit_control::cr3_place > {
  static const char* value()
  {
    return "e0ef97c03b97cee334a02acaeaf0f059";
  }

  static const char* value(const ::cr3_moveit_control::cr3_place&) { return value(); }
};

template<>
struct DataType< ::cr3_moveit_control::cr3_place > {
  static const char* value()
  {
    return "cr3_moveit_control/cr3_place";
  }

  static const char* value(const ::cr3_moveit_control::cr3_place&) { return value(); }
};


// service_traits::MD5Sum< ::cr3_moveit_control::cr3_placeRequest> should match
// service_traits::MD5Sum< ::cr3_moveit_control::cr3_place >
template<>
struct MD5Sum< ::cr3_moveit_control::cr3_placeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cr3_moveit_control::cr3_place >::value();
  }
  static const char* value(const ::cr3_moveit_control::cr3_placeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cr3_moveit_control::cr3_placeRequest> should match
// service_traits::DataType< ::cr3_moveit_control::cr3_place >
template<>
struct DataType< ::cr3_moveit_control::cr3_placeRequest>
{
  static const char* value()
  {
    return DataType< ::cr3_moveit_control::cr3_place >::value();
  }
  static const char* value(const ::cr3_moveit_control::cr3_placeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cr3_moveit_control::cr3_placeResponse> should match
// service_traits::MD5Sum< ::cr3_moveit_control::cr3_place >
template<>
struct MD5Sum< ::cr3_moveit_control::cr3_placeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cr3_moveit_control::cr3_place >::value();
  }
  static const char* value(const ::cr3_moveit_control::cr3_placeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cr3_moveit_control::cr3_placeResponse> should match
// service_traits::DataType< ::cr3_moveit_control::cr3_place >
template<>
struct DataType< ::cr3_moveit_control::cr3_placeResponse>
{
  static const char* value()
  {
    return DataType< ::cr3_moveit_control::cr3_place >::value();
  }
  static const char* value(const ::cr3_moveit_control::cr3_placeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CR3_MOVEIT_CONTROL_MESSAGE_CR3_PLACE_H
