// Generated by gencpp from file cr3_moveit_control/PickWithSideResponse.msg
// DO NOT EDIT!


#ifndef CR3_MOVEIT_CONTROL_MESSAGE_PICKWITHSIDERESPONSE_H
#define CR3_MOVEIT_CONTROL_MESSAGE_PICKWITHSIDERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cr3_moveit_control
{
template <class ContainerAllocator>
struct PickWithSideResponse_
{
  typedef PickWithSideResponse_<ContainerAllocator> Type;

  PickWithSideResponse_()
    : success_grasp(false)  {
    }
  PickWithSideResponse_(const ContainerAllocator& _alloc)
    : success_grasp(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_grasp_type;
  _success_grasp_type success_grasp;





  typedef boost::shared_ptr< ::cr3_moveit_control::PickWithSideResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cr3_moveit_control::PickWithSideResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PickWithSideResponse_

typedef ::cr3_moveit_control::PickWithSideResponse_<std::allocator<void> > PickWithSideResponse;

typedef boost::shared_ptr< ::cr3_moveit_control::PickWithSideResponse > PickWithSideResponsePtr;
typedef boost::shared_ptr< ::cr3_moveit_control::PickWithSideResponse const> PickWithSideResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cr3_moveit_control::PickWithSideResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cr3_moveit_control::PickWithSideResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cr3_moveit_control::PickWithSideResponse_<ContainerAllocator1> & lhs, const ::cr3_moveit_control::PickWithSideResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success_grasp == rhs.success_grasp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cr3_moveit_control::PickWithSideResponse_<ContainerAllocator1> & lhs, const ::cr3_moveit_control::PickWithSideResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cr3_moveit_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cr3_moveit_control::PickWithSideResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cr3_moveit_control::PickWithSideResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cr3_moveit_control::PickWithSideResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cr3_moveit_control::PickWithSideResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cr3_moveit_control::PickWithSideResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cr3_moveit_control::PickWithSideResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cr3_moveit_control::PickWithSideResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "577d982bd0a0b3cbfd60d744c63e2b3e";
  }

  static const char* value(const ::cr3_moveit_control::PickWithSideResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x577d982bd0a0b3cbULL;
  static const uint64_t static_value2 = 0xfd60d744c63e2b3eULL;
};

template<class ContainerAllocator>
struct DataType< ::cr3_moveit_control::PickWithSideResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cr3_moveit_control/PickWithSideResponse";
  }

  static const char* value(const ::cr3_moveit_control::PickWithSideResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cr3_moveit_control::PickWithSideResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success_grasp\n"
;
  }

  static const char* value(const ::cr3_moveit_control::PickWithSideResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cr3_moveit_control::PickWithSideResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success_grasp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PickWithSideResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cr3_moveit_control::PickWithSideResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cr3_moveit_control::PickWithSideResponse_<ContainerAllocator>& v)
  {
    s << indent << "success_grasp: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success_grasp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CR3_MOVEIT_CONTROL_MESSAGE_PICKWITHSIDERESPONSE_H
