// Generated by gencpp from file cr3_moveit_control/PickWithSide.msg
// DO NOT EDIT!


#ifndef CR3_MOVEIT_CONTROL_MESSAGE_PICKWITHSIDE_H
#define CR3_MOVEIT_CONTROL_MESSAGE_PICKWITHSIDE_H

#include <ros/service_traits.h>


#include <cr3_moveit_control/PickWithSideRequest.h>
#include <cr3_moveit_control/PickWithSideResponse.h>


namespace cr3_moveit_control
{

struct PickWithSide
{

typedef PickWithSideRequest Request;
typedef PickWithSideResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PickWithSide
} // namespace cr3_moveit_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cr3_moveit_control::PickWithSide > {
  static const char* value()
  {
    return "7ea0fce5a9928bbcaeb661887a26e9f1";
  }

  static const char* value(const ::cr3_moveit_control::PickWithSide&) { return value(); }
};

template<>
struct DataType< ::cr3_moveit_control::PickWithSide > {
  static const char* value()
  {
    return "cr3_moveit_control/PickWithSide";
  }

  static const char* value(const ::cr3_moveit_control::PickWithSide&) { return value(); }
};


// service_traits::MD5Sum< ::cr3_moveit_control::PickWithSideRequest> should match
// service_traits::MD5Sum< ::cr3_moveit_control::PickWithSide >
template<>
struct MD5Sum< ::cr3_moveit_control::PickWithSideRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cr3_moveit_control::PickWithSide >::value();
  }
  static const char* value(const ::cr3_moveit_control::PickWithSideRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cr3_moveit_control::PickWithSideRequest> should match
// service_traits::DataType< ::cr3_moveit_control::PickWithSide >
template<>
struct DataType< ::cr3_moveit_control::PickWithSideRequest>
{
  static const char* value()
  {
    return DataType< ::cr3_moveit_control::PickWithSide >::value();
  }
  static const char* value(const ::cr3_moveit_control::PickWithSideRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cr3_moveit_control::PickWithSideResponse> should match
// service_traits::MD5Sum< ::cr3_moveit_control::PickWithSide >
template<>
struct MD5Sum< ::cr3_moveit_control::PickWithSideResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cr3_moveit_control::PickWithSide >::value();
  }
  static const char* value(const ::cr3_moveit_control::PickWithSideResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cr3_moveit_control::PickWithSideResponse> should match
// service_traits::DataType< ::cr3_moveit_control::PickWithSide >
template<>
struct DataType< ::cr3_moveit_control::PickWithSideResponse>
{
  static const char* value()
  {
    return DataType< ::cr3_moveit_control::PickWithSide >::value();
  }
  static const char* value(const ::cr3_moveit_control::PickWithSideResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CR3_MOVEIT_CONTROL_MESSAGE_PICKWITHSIDE_H
